### PR TITLE
(PDB-3193) Fix beaker AWS duplicate keys

### PR DESCRIPTION
**Pull request by kbarber**
This is just a branch for me to use while we fix the beaker issue on beaker master branch.

### CODE REVIEW

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this platform

**Comment by senior** [comment]
@kbarber what's the status on this? We're still getting a lot of failures on this

**Pull request merged**
