### PR TITLE
(maint) speed up include total

### PR DESCRIPTION
**Pull request by wkalt**

### CODE REVIEW

**Comment by wkalt** [comment]
On a small PE master:

before:
```
root@wyatt-centos-master:~[root@wyatt-centos-master ~]# time curl -X GET http://localhost:8080/pdb/query/v4 -d 'query=reports{limit 50}' > /dev/null -d 'include_total=true'
real  0m4.727s
```

after:
```
real  0m0.249s
```
This should make several pages in the console load faster.

**Comment by wkalt** [comment]
also, depends on https://github.com/puppetlabs/puppetdb/pull/2231

**Comment by wkalt** [comment]
@puppetlabs-jenkins retest this please

**Comment by wkalt** [comment]
this has a bug

**Comment by mullr** [comment]
@wkalt any update on this? Also, do you have before / after query plans handy?

**Comment by wkalt** [comment]
@mullr unfortunately I've forgotten what I was referring to with my ominous comment. I'll poke around and get back to you in a bit.

**Comment by wkalt** [comment]
current include_total plan for reports: https://gist.github.com/wkalt/7e32c2cdcd1b7d2a760c4e7d4d4b26d3

new plan: https://gist.github.com/wkalt/b2dfd446a357ef9252e82bfa200e26a1

Interestingly the difference seems to go away at some level of scale. If I run the first query on my 60k node dataset, I get the second plan with just a seq scan.

**Comment by wkalt** [comment]
also, I think the bug I mentioned above was me mistakenly connecting to the wrong database and getting confused. This is good now as far as I can see.

**Comment by mullr** [comment]
@wkalt merged the 'costly join' PR, can you rebase?

**Comment by wkalt** [comment]
I think we should unrevert #2231 to fix that issue with group_by and paging

**Comment by wkalt** [comment]
then this should go in cleanly

**Pull request closed without merging**
