### PR TITLE
DO NOT MERGE REVIEW ONLY (PDB-2386) Add Ubuntu 15.10 to PuppetDB's CI pipeline

### PR DESCRIPTION
**Pull request by kurtwall**
Add a Beaker config file; update install dependencies in the pre-suite; add a stanza for the new AMI to the EC2 image file; add to the COW list and the S3 export.

### CODE REVIEW

**Comment by wkalt** [comment]
@puppetlabs-jenkins test this please

**Comment by kbarber** [comment]
@kurtwall its subtle to see, but what really happened here, was the packaging step failed. It just doesn't return a red, so acceptance continues.

I figured this out, first by analyzing the packaging step: https://jenkins-enterprise.delivery.puppetlabs.net/job/enterprise_puppetdb_packaging_stable/312/console

In there you can see 'FAILED' and a link to the job over in release land: http://jenkins-release.delivery.puppetlabs.net/job/puppetdb-packaging-2016-02-11-08-39-08-3.2.4.SNAPSHOT.2016.02.11T0839/

Looks like to me, there is something not quite right in release land, for what we've done: http://jenkins-release.delivery.puppetlabs.net/job/puppetdb-packaging-2016-02-11-08-39-08-3.2.4.SNAPSHOT.2016.02.11T0839/command=pl_deb%20COW=base-wily-amd64.cow/1/console

**Comment by kbarber** [comment]
This failure seems to be due to the fact we are lacking 'wily' cows for pbuilder, looks like we need to put in a request for this.

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@kurtwall it sounds like we might end up skipping 15.10, this patch right now needs puppet-server to have its own builds for 15.10 first which is the gotcha. Can you find out how likely 15.10 is? If puppet-server intend to do this or not basically. If its 16.04 only, then we might as well close this ticket.

**Comment by kurtwall** [comment]
I'm closing this PR because RE is signaling they won't do the associated work for packages and COWs before 15.10 goes EOL.

**Pull request closed without merging**
