### PR TITLE
(maint) merge up 7.x

### PR DESCRIPTION
**Pull request by jonathannewman**
* 7.x:
  Set clj-parent=5.4.0
  (maint) update ezbake to 2.5.2

### CODE REVIEW

**Review by steveax — APPROVED** [review]
👍

**Comment by jonathannewman** [comment]
Ok, I added a basic Yaml parser based on snakeyaml 2.0, and updated the one test that was using it.

**Comment by jonathannewman** [comment]
The puppet server 7.x tests are odd.  Why aren't we running against puppet 8 server?

**Comment by jonathannewman** [comment]
The acceptance test failures are due to RH8 openjdk no longer including tzdata-java.  These failures seem beyond this PR.  Going to merge with those tests failing.

**Pull request merged**
