### PR TITLE
WIP: (PDB-950) Catch and express postgresql regexp failures as better errors

### PR DESCRIPTION
**Pull request by DemonShi**
This commit adds a validation for regexps in queries as was proposed in PDB-950

### CODE REVIEW

**Comment by kbarber** [comment]
@DemonShi I've been absent and missed your last question: I have no specific deadline on this one. In regards to performance testing, we have nothing specific for queries today that we use, its usually bespoke - one could use an external testing tool, or do the test in clojure without the networking traffic so you can iterate in a tight loop. I'm not sure if this change needs something heavier than this today, its easy enough to observe a potential change and conjecture as well :-).

**Comment by DemonShi** [comment]
@kbarber Oh, I've been pretty busy and also had pretty long holidays here too.

According to the PR: I developed a solution that tries to take a first item from result-set lazy sequence under try/catch and resolves a promise with nil. If there is an exception, I resolve that promise with exception from DB.
Then from the "ring" thread we can wait until promise is ready (basically, that is the moment right after we took a first item from result-set or nothing - when result-set is empty) and say whether query was successful or not. If query failed - we re-throw the exception and follow normal error processing (the same way as if there was a count-query). If query is okay - continue execution.

Here is code snippet just to get your opinion of the approach:
```
(jdbc/with-transacted-connection db
      (let [{[sql & params] :results-query
             count-query :count-query
             projections :projections} (query->sql version query
                                                   paging-options)
             resp-error (promise)
             resp (output-fn
                   (fn [f]
                     (try
                       (jdbc/with-transacted-connection db
                         (query/streamed-query-result version sql params
                           (comp
                             f
                             #(do
                                (first %)
                                (deliver resp-error nil)
                                %)
                             (munge-fn version projections))))
                       (catch Exception e
                         (deliver resp-error e)
                         (throw e)))))]
        (when @resp-error
          (println (str "SQL error occured: " (.getMessage @resp-error)))
          (throw @resp-error))
        (if count-query
          (http/add-headers resp {:count (jdbc/get-result-count count-query)})
          resp)))))
```

I still need to refactor it a bit, check corner cases and cover it with tests, but the idea of the approach should be clear.

What do you think?

**Comment by DemonShi** [comment]
@puppetcla, I signed CLA

**Comment by kbarber** [comment]
@DemonShi I think this sounds interesting, it looks to me like this should be okay in theory - and it looks like this is only done on the first item in the response only which is great. As long as it doesn't try to realize the lazy-seq at any point (ie. it keeps it as a lazy-seq and just does this on the first item for example) then it should be fine.

**Comment by DemonShi** [comment]
@pljenkinsro test this please

**Comment by DemonShi** [comment]
Couple of questions:
1. Should I write http tests for each endpoint that supports regexps?
2. Should I combine my main commit with travis-related commit?

**Comment by kbarber** [comment]
@pljenkinsro retest this please

**Comment by kbarber** [comment]
@DemonShi to answer your questions:

1. no, this is enough
2. no, this is fine for now
3. yes, well - you should be able to? No idea, I can look into github permissions.

**Comment by kbarber** [comment]
thats a PASS, only a rubygems transient is being thrown ^^.

**Comment by kbarber** [comment]
Merged manually, with some small cleanups and the extra tests.

**Pull request closed without merging**
