### PR TITLE
(QENG-5135) Bump ezbake to 1.1.10 in 4.4.x

### PR DESCRIPTION
**Pull request by demophoon**

### CODE REVIEW

**Comment by wkalt** [comment]
@demophoon you've got two open PRs with this title -- not sure which is which

**Comment by wkalt** [comment]
@puppetlabs-jenkins retest this please

**Comment by demophoon** [comment]
@wkalt I'm not sure if this is something that should be merged up or opened on multiple branches of the project so both PRs are targeted at different branches.

**Comment by wkalt** [comment]
@demophoon most likely this is fine and will get rolled up, but I'll defer to @mullr

**Comment by demophoon** [comment]
@mullr // @wkalt Is there anything that I can do to help get this in?

**Pull request merged**
