### PR TITLE
(PDB-5500) Fix bad class titles in PQL tutorial docs

### PR DESCRIPTION
**Pull request by arjenz**

### CODE REVIEW

**Comment by stelcodes** [comment]
Hey @arjenz, these docs refer to the official Puppet [Apache module](https://forge.puppet.com/modules/puppetlabs/apache). Is that what you're using? I believe lowercase is appropriate in this case.

**Comment by arjenz** [comment]
> 

Yes I am, I don't think it matters though, I believe all the resources in the database of type `Class` start with a capital letter (by design, I assume). 
Locally for me it shows because with a capital letter the search yields results (whereas searching for `apache` finds nothing), also shown in other parts of the documentation, like https://puppet.com/docs/puppetdb/7/api/query/examples-pql.html#fact-and-resource-filtering-for-classes

**Comment by arjenz** [comment]
> Hey @arjenz, these docs refer to the official Puppet [Apache module](https://forge.puppet.com/modules/puppetlabs/apache). Is that what you're using? I believe lowercase is appropriate in this case.

Yes I am, I don't think it matters though, I believe all the resources in the database of type Class start with a capital letter (by design, I assume).
Locally for me it shows because with a capital letter the search yields results (whereas searching for apache finds nothing), also shown in other parts of the documentation, like https://puppet.com/docs/puppetdb/7/api/query/examples-pql.html#fact-and-resource-filtering-for-classes

**Comment by stelcodes** [comment]
@arjenz Ah ok yes this should be fixed. Thanks for noticing this! I've made a ticket for the issue [here](https://tickets.puppetlabs.com/browse/PDB-5500). Would you mind changing the commit message to `(PDB-5500) Fix bad class titles in PQL tutorial docs`? Then I'll be able to rebase your commit straight onto `6.x`.  Thanks so much for the contribution.

**Comment by arjenz** [comment]
@stelcodes Thank you, done and done!

**Review by stelcodes — APPROVED** [review]

**Pull request merged**
