### PR TITLE
(RE-8457) Update to ship to puppet5 repos

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
built with:
```
git clean -ffdx ; lein clean ; lein install ; EZBAKE_ALLOW_UNREPRODUCIBLE_BUILDS=true EZBAKE_NODEPLOY=true lein with-profile ezbake ezbake build
```

gave me this build job:
http://jenkins-release.delivery.puppetlabs.net/job/puppetdb-packaging-2017-09-27-00-30-14-5.1.1.SNAPSHOT.2017.09.27T0030/

which dropped artifacts at:
http://builds.puppetlabs.lan/puppetdb/5.1.1.SNAPSHOT.2017.09.27T0030/artifacts/

tested with:
```
APT_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
APT_SIGNING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
APT_STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
DMG_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
DMG_STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
GEM_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
IPS_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
MSI_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
MSI_STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
NUGET_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
P5P_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
SWIX_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
SWIX_STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
SVR4_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
TAR_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
TAR_STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
YUM_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
YUM_STAGING_SERVER=oqcod8kmrz9f4px.delivery.puppetlabs.net \
INTERNAL_GEM_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
INTERNAL_NEXUS_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
INTERNAL_STICKLER_HOST=oqcod8kmrz9f4px.delivery.puppetlabs.net \
rake pl:jenkins:uber_ship
```

I had to manually grab files from http://builds.puppetlabs.lan/puppetdb/5.1.1.SNAPSHOT.2017.09.27T0030/artifacts/ because I'm not shipping from a tag. This will be an issue with nightlies.

this produced:
```

```

**Comment by melissa** [comment]
@mwaggett the tar sign task failed, because:
```
File.exist?("pkg/#{Pkg::Config.project}-#{Pkg::Config.version}.tar.gz") or fail "No tarball exists. Try rake package:tar?"
```

`Pkg::Config.version` here doesn't equal `5.1.2.SNAPSHOT.2017.09.26T2349` because of how ezbake versions artifacts.

**Comment by melissa** [comment]
I'd like to see https://cinext-jenkinsmaster-enterprise-prod-1.delivery.puppetlabs.net/view/pe-integration/view/pe-2018.1.x/job/enterprise_pe-acceptance-tests_integration-system_pe_full-pre-upgrade_nightly_2018.1.x/ finish green, but currently the failure looks unrelated to this change on puppet-agent.

**Comment by mwaggett** [comment]
@melissa What's the status of this? Looks like that build has gone green, but not sure how to rekick the Travis and Jenkins tests. Maybe rebase?

**Comment by melissa** [comment]
Jenkins retest this please

**Comment by melissa** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
