### PR TITLE
(PDB-2461) Release notes for 3.2.4

### PR DESCRIPTION
**Pull request by mullr**

### CODE REVIEW

**Comment by senior** [comment]
@mullr isn't this missing the packaging changes, which is the primary reason for the release?

**Comment by mullr** [comment]
@senior I don't know anything about that. Can you enlighten me?

**Comment by senior** [comment]
AFAIK, [RE-6278](https://tickets.puppetlabs.com/browse/RE-6278) is the real reason we're doing a release, maybe @wkalt or @rbrw can correct me here if I'm wrong.

**Comment by senior** [comment]
@mullr should this be closed?

**Pull request closed without merging**
