### PR TITLE
[WIP] (PDB-2475) Add Xenial and Wily to build/test pipelines

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by kbarber** [comment]
You might get failures in the initial setup pre_tasks of beaker, once this actually runs on a xenial host fwiw: https://github.com/puppetlabs/puppetdb/blob/master/acceptance/setup/pre_suite/40_install_deps.rb#L70-L76

**Comment by melissa** [comment]
@kbarber thanks for pointing that out. I've updated the PR to take that into account

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@puppetlabs-jenkins test this please

**Comment by wkalt** [comment]
@puppetlabs-jenkins test this please

**Comment by melissa** [comment]
Did the tests run against 15.10 and 16.04?

**Pull request merged**
