### PR TITLE
(maint) Update beaker to ~3.4, unpin from 2.30.1

### PR DESCRIPTION
**Pull request by kbarber**
Signed-off-by: Ken Barber <ken@bob.sh>

### CODE REVIEW

**Comment by senior** [comment]
@kbarber looks like the version bump causes gem conflicts

**Comment by kbarber** [comment]
@senior actually, looks like we need to use a newer ruby on the slaves, let me dig in when I have some time.

**Comment by rbrw** [comment]
May not be quite the same thing, but Wyatt just pinned a gem to fix a similar error in stable and master 39f423d3ffad0ba61169e3411cab65587f8c6f81

**Comment by kbarber** [comment]
@rbrw well, for this PR I'll have to remove the pinning (when we get ruby 2) I guess now so thanks.

**Comment by kbarber** [comment]
I've raised a PR for CI here: https://github.com/puppetlabs/ci-job-configs/pull/2039 with the intent to have it switch to ruby 2.3.1.

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
