### PR TITLE
(PDB-2438) Fix pretty-printing parameter for POST

### PR DESCRIPTION
**Pull request by ajroetker**
This commit fixes our `pretty` parameter for query POSTs, before this
commit we weren't properly passing the param from the POST body to the
produce-streaming-body function and weren't allowing the parameter
through validation.

### CODE REVIEW

**Comment by senior** [comment]
I'll review/test this

**Comment by senior** [comment]
running 
```
curl "http://localhost:8080/pdb/query/v4/nodes?pretty=true"
```
Doesn't give me formatted JSON and it doesn't work on master. Looks like it's broken and maybe needs a test to validate?

**Comment by senior** [comment]
This works:
```
$  curl -X POST http://localhost:8080/pdb/query/v4/nodes \
  -H 'Content-Type:application/json' \
  -d '{"query":["~","certname",".*"], "pretty": true}''
```
so it might just affect GETs

**Comment by ajroetker** [comment]
added a test!

**Comment by senior** [comment]
@ajroetker looks like legit Travis failures

**Comment by senior** [comment]
:+1: will merge when the pipeline is clear

**Pull request merged**
