### PR TITLE
(PDB-1459) Support extract with no subexpression

### PR DESCRIPTION
**Pull request by ajroetker**
This commit adds support for extracts with no subexpression.

### CODE REVIEW

**Comment by kbarber** [comment]
@ajroetker do we have any tests for this? I see we cleaned up a test, but there are no new tests, or am I missing something?

**Comment by ajroetker** [comment]
@kbarber added some tests for ya ;)

**Comment by wkalt** [comment]
this needs docs updates

**Comment by wkalt** [comment]
also shouldn't this work?
```
curl -X GET http://localhost:8080/pdb/query/v4/facts -d 'query=["extract","certname"]'
```

**Comment by ajroetker** [comment]
@wkalt should be all good now!

**Pull request merged**
