### PR TITLE
(PDB-1102) Upgrade to activemq 5.10.1

### PR DESCRIPTION
**Pull request by rbrw**

### CODE REVIEW

**Comment by senior** [comment]
@pljenkinsro retest this please

**Comment by rbrw** [comment]
@pljenkinsro retest this please

**Comment by rbrw** [comment]
@senior ran in to intermittent failures, which I can corroborate.  Running "lein test" failed one time out of 18 here, and then when I let it go further, 6 times out of 28.  At least one of the failures looked like this:

```
Caused by: clojure.lang.ExceptionInfo: throw+: "Results not found after 100 iterations, giving up"
 at puppetlabs.puppetdb.cli.import_export_roundtrip_test$block_until_results_fn.invoke (import_export_roundtrip_test.clj:49)
    puppetlabs.puppetdb.cli.import_export_roundtrip_test$block_on_node$fn__25178.invoke (import_export_roundtrip_test.clj:76)
    clojure.core$binding_conveyor_fn$fn__4145.invoke (core.clj:1910)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:262)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:615)
    java.lang.Thread.run (Thread.java:745)
```

**Comment by kbarber** [comment]
@rbw @senior out of curiosity, have we tried an older version of amq, to see if this issue can be bisected to a particular new revision by any chance?

**Comment by kbarber** [comment]
Or a newer version: http://activemq.apache.org/activemq-5110-release.html

**Comment by kbarber** [comment]
Closing this for now, since we're punting this out: https://tickets.puppetlabs.com/browse/PDB-1102

**Pull request closed without merging**
