### PR TITLE
(PE-19944) Update clj-i18n to 0.8.0

### PR DESCRIPTION
**Pull request by ajroetker**
This commit updates the i18n scaffolding arounding PuppetDB to be in
line with the latest.

### CODE REVIEW

**Comment by camlow325** [comment]
@ajroetker I talked with @senior about this today.  He's good with us just bumping up to the latest clj-parent, currently 0.6.0.  This would pull in i18n 0.8.0, as well as trapperkeeper-metrics 1.0.  My team's working this sprint on bumping all PE components up to clj-parent 0.6.0+ / tk-metrics 1.0 as well.

I've run the unit tests locally with your changes, just swapping in the newer clj-parent version.  Would you be open to just updating this PR to use clj-parent 0.6.0 instead?

**Comment by ajroetker** [comment]
@camlow325 Done!

**Comment by camlow325** [comment]
@ajroetker Awesome, thank you!

**Comment by wkalt** [comment]
@ajroetker this needs the pot/po changes removed

**Comment by mullr** [comment]
@ajroetker I hijacked your PR while fixing it up, sorry about stealing the credit :hamster:

**Pull request merged**
