### PR TITLE
(PDB-2524) Data-driven dashboard

### PR DESCRIPTION
**Pull request by mullr**
Rework the dashboard to get the list of meters to display in a request to the
server, rather than hardcoding them in javascript. This has several benefits:

- All metrics can be returned in a single response, instead of having to poll
  each metric individually

- The meter descriptions can be localized

- The data can be overriden in PE, to allow new meters to be added there for
  PE-only functionality.

### CODE REVIEW

**Comment by mullr** [comment]
If anybody reviews this: the sketchiest part, to me, is the format of the meter defs; it has some data for sever-side processing, and some stuff meant for the client.

**Comment by mullr** [comment]
@puppetlabs-jenkins retest this please

**Comment by wkalt** [comment]
One thing I'm noticing about this is the batched request seems to make the initial page load much slower. I'm not sure if it's worth addressing though.

**Comment by mullr** [comment]
@wkalt yeah, it probably will. I guess I could change it to read the meters directly rather than going through jmx, but I doubt that's worth the effort.

**Comment by wkalt** [comment]
+1 will merge after travis passes

**Pull request merged**
