### PR TITLE
(maint) Add skeletor team as codeowners

### PR DESCRIPTION
**Pull request by donoghuc**

### CODE REVIEW

**Review by shaigy — APPROVED** [review]

**Comment by donoghuc** [comment]
@austb

**Comment by jonathannewman** [comment]
Did you want this against 7.x?

**Comment by donoghuc** [comment]
I thought codeowners respects the default branch? (which is main)

**Comment by jonathannewman** [comment]
I'm pretty sure it is per-branch:  https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location

**Comment by jonathannewman** [comment]
>Each CODEOWNERS file assigns the code owners for a single branch in the repository. Thus, you can assign different code owners for different branches, such as @octo-org/codeowners-team for a code base on the default branch and @octocat for a GitHub Pages site on the gh-pages branch.

**Comment by donoghuc** [comment]
Updated. Will figure out a mergeup once this lands.

**Comment by jonathannewman** [comment]
@donoghuc merged!

**Pull request merged**
