### PR TITLE
(PDB-1698) Move import/export/anonymization acceptance tests to Clojure

### PR DESCRIPTION
**Pull request by ajroetker**
This PR moves all the import/export/anonymization acceptance tests to Clojure.

This PR also moves the anonymization tool to the export endpoint.

This PR changes the export tool to export in 4 queries (on PSQL) instead of `(+ 1 (* 3 (count nodes)))`.

### CODE REVIEW

**Comment by ajroetker** [comment]
@pljenkins retest this please

**Comment by ajroetker** [comment]
@pljenkinsro retest this please

**Comment by wkalt** [comment]
how much trouble would it be to split this into a PR for the test reimplementation, and another for the anonymization reimplementation (with a different ticket)? This seems like it goes a bit beyond PDB-1732.

**Comment by ajroetker** [comment]
Will work on splitting this PR up and a deprecation PR for anonymization

**Pull request closed without merging**
