### PR TITLE
(tests) Don't try to install rubygems package on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by kurtwall**
Rubygems on Ubuntu 14.04 Trusty is now part of the ruby package.

Change name of new config file for Ubuntu 14.04 Trusty.

Work done in support of PDB-997.

### CODE REVIEW

**Comment by kbarber** [comment]
@puppetlabs-jenkins test this please

**Comment by kurtwall** [comment]
@puppetlabs-jenkins test this pretty please

**Comment by kurtwall** [comment]
Does this get merged now?

**Comment by kbarber** [comment]
@kurtwall no, it never tested ubuntu 14.04, and thus the PR test proved nothing so far. I'll rerun now.

**Comment by kbarber** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
@kurtwall thats about to fail, I think we're missing something when we push to S3 for later download:

https://github.com/puppetlabs/puppetdb/blob/stable/ext/jenkins/packaging.sh#L63

I think we just need to add 'trusty' to that list.

**Comment by kurtwall** [comment]
@puppetlabs-jenkins retest this please

**Comment by kurtwall** [comment]
@puppetlabs-jenkins retest this please

**Comment by kbarber** [comment]
Squashed and merged manually: https://github.com/puppetlabs/puppetdb/commit/0833a5713c9e36268e36912ecc742c408e5c494f

**Pull request closed without merging**
