### PR TITLE
(PDB-3306) Remove clj cli import/export (superceded by rust)

### PR DESCRIPTION
**Pull request by rbrw**

### CODE REVIEW

**Comment by mullr** [comment]
@rbrw need to update acceptance tests here, I think one of them is checking for the CLI

**Comment by mullr** [comment]
@rbrw There's a reference to the old command in anonymization.markdown that needs cleaning up

**Comment by mullr** [comment]
otherwise :+1: from me

**Comment by rbrw** [comment]
Merging, given Russ's approval for everything but the docs, and a separate ticket for that: https://tickets.puppetlabs.com/browse/PDB-3499

**Pull request merged**
