### PR TITLE
Merge 5.2.x -> 6.0.x

### PR DESCRIPTION
**Pull request by mwaggett**
Conflicts were resolved by taking changes from 5.2.x.

### CODE REVIEW

**Comment by mwaggett** [comment]
there might be an issue, throwing a 'don't merge' on here until that gets figured out

**Comment by robdaemon** [comment]
@mwaggett I see two issues on the Mac builds, but we know about them - they're not related to your change. What are you seeing?

**Comment by mwaggett** [comment]
@robdaemon When this change got merged into puppetserver, they had some install issues ([RE-12082](https://tickets.puppetlabs.com/browse/RE-12082)). I'm planning to investigate today.

**Comment by Zak-Kent** [comment]
Sorry, just noticed the review request. I did see that the change to 5.2.x is having issues with our acceptance tests in jenkins. This looks like the job that was failing when stuff got merged originally: [here](https://cinext-jenkinsmaster-enterprise-prod-1.delivery.puppetlabs.net/job/enterprise_puppetdb_integration-system-puppetdb_full-5.2.x/765/)

I ran the job again without the ezbake bump and it has the same error now, though only on the 5.2.x branch. Maybe it's the same issue you mentioned in puppetserver?

**Comment by mwaggett** [comment]
yeah, sorry, I should've reverted the bump in 5.2.x. I can do that now.

**Comment by Zak-Kent** [comment]
no worries, I'm not sure reverting the bump in our project will fix it. I tried to run the tests with vmpooler locally and got the same error with the older version of ezbake.

**Comment by mwaggett** [comment]
I'm just gonna close this and open a new one when the time comes.

**Pull request closed without merging**
