### PR TITLE
(PDB-2950) Require PostgreSQL >= 9.6

### PR DESCRIPTION
**Pull request by mullr**
- Update the minimum version vector to [9 6].

- Refactor version check functions to allow the minimum version to be overriden
  if necessary (temporary internal hook, for use by PE)

- Fix a bug that was preventing version-check test assertions from running

### CODE REVIEW

**Comment by mullr** [comment]
@puppetlabs-jenkins retest this please

**Comment by rbrw** [comment]
I'll test this in the morning, but it looks pretty good.

**Comment by rbrw** [comment]
Here at least, this hangs when run against 9.4, after printing the warning.  It might be a local issue, but we should double check, because it's one of the dreaded "C-c and C-\ can't kill it", failures.

**Comment by rbrw** [comment]
Looks good given the ticket to deal with the shutdown hang.

**Pull request merged**
