### PR TITLE
use HTTPS for update check (updates.puppetlabs.com)

### PR DESCRIPTION
**Pull request by hex2a**

### CODE REVIEW

**Comment by mullr** [comment]
@puppetlabs-jenkins test this please

**Comment by rbrw** [comment]
@ajroetker See any problem switching to https by default for update checks?

**Comment by ajroetker** [comment]
@rbrw Nothing I can think of!

**Comment by joshcooper** [comment]
If we make a secure SSL connection, are we sure the clojure client making the SSL connection has the root cert used to issue the SSL cert for `updates.puppetlabs.com`?

**Comment by mullr** [comment]
@puppetlabs-jenkins test this please

**Pull request merged**
