### PR TITLE
(BKR-147) add Gemfile setting for BEAKER_VERSION for puppet, ...

### PR DESCRIPTION
**Pull request by anodelman**
... puppetdb, etc

- add support for BEAKER_VERSION env var, simplifies configuring
  beaker across jenkins

### CODE REVIEW

**Comment by wkalt** [comment]
@pljenkinsro okay to test

**Comment by kbarber** [comment]
@pljenkinsro test this please

**Comment by anodelman** [comment]
Failed test unrelated to patch.

**Comment by mullr** [comment]
@pljenkinsro retest this please

**Pull request merged**
