### PR TITLE
(linting) Remove all the unused namespace declarations

### PR DESCRIPTION
**Pull request by ajroetker**
This commit removes all the unecessary namespace declarations found
using eastwood.

### CODE REVIEW

**Comment by ajroetker** [comment]
@pljenkinsro retest this please

**Comment by ajroetker** [comment]
@pljenkinsro retest this please

**Comment by ajroetker** [comment]
@pljenkinsro retest this please

**Comment by ajroetker** [comment]
@pljenkinsro retest this please

**Comment by rbrw** [comment]
@pljenkinsro retest this please

**Comment by rbrw** [comment]
Looks good to me.

**Pull request merged**
